apiVersion: apps/v1
kind: Deployment
metadata:
  name: rust-api
  namespace: weather-tweets
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rust-api
  template:
    metadata:
      labels:
        app: rust-api
    spec:
      containers:
      - name: rust-api
        image: fercho913/rust-api:latest # Tu imagen de Docker Hub
        ports:
        - containerPort: 8080
        imagePullPolicy: IfNotPresent
        env:
        - name: APP_GO_SERVICE_URL
          value: "http://go-entrypoint:80/input" # URL del Service Go Entrypoint
        - name: RUST_LOG  # <--- ¡Variable RUST_LOG añadida aquí!
          value: "info"   # <--- Seteamos el nivel de logging a 'info'

---

apiVersion: v1
kind: Service
metadata:
  name: rust-api
  namespace: weather-tweets
spec:
  selector:
    app: rust-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: rust-api-hpa
  namespace: weather-tweets
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: rust-api
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 30